# Default values for docker-registry-ui.
ui:
  # title of the registry
  title: "Docker registry UI"
  # allow delete of images
  delete_images: false
  # UI behave as a proxy of the registry
  proxy: true

  # DIG: add controll for not static images for multi/single registry, set true if you dont want that registry urls can be added from the UI
  single_registry: false

  replicaCount: 1
  image:
    registry: docker.io
    repository: joxit/docker-registry-ui
    tag: 2.0
    pullPolicy: Always
  probe:
    liveness: true
    readiness: true

  resources: {}
  # If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: docker-registry-ui.local

    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

registry:
  url: https://example.com:5000

imagePullSecrets: []
nameOverride: ""
